forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apache'
mod 'puppetlabs/mysql'
mod 'thias/php'
mod 'willdurand/composer'
mod 'jfryman/selinux'
mod 'hdeadman/puppet-wp',
  :git => "https://github.com/hdeadman/puppet-wp"

mod 'jacobhenke/appdev',
  :git => "git://github.com/jacobhenke/appdev-for-librarianandvagrant"
