forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/apache'
mod 'puppetlabs/mysql'
mod 'thias/php'
mod 'willdurand/composer'
mod 'spiette/selinux'
mod 'rmccue/wp'
mod 'distractedio/appdev',
  :git => "git://github.com/jacobhenke/appdev-for-librarianandvagrant"
